### ISSUE TITLE
Forget

### ISSUE THREAD

**Issue by ThiloL** [anakic/Jot#10]
Is there a functionality to forget all or certain settings. I want to implement something like "my.exe -ResetAll" to forget settings.

**Comment by anakic** [comment]
Sorry for the late reply. 

To answer your question: not yet, no. Should not be difficult to implement, though. 

I think it should be implemented on two levels:
- at the IStore level for clearing specific object settings
- at the IStoreFactory level for clearing settings for all objects

If you have time, I wouldn't mind if you made a pull request with this. If not, that's fine, I'll probably get to it eventually.

**Comment by ms-somanna** [comment]
Is this feature implemented yet?

**Comment by anakic** [comment]
No, but I'll get to it in a few days. Will reply back here once it's done.

**Comment by anakic** [comment]
@SwaroopSomanna Just got to this. Solved and pushed a new NuGet package. The tracker now has a `Forget(object target)` method for forgetting individual target settings and a `ForgetAll()` for forgetting all saved state. Let me know if this works as expectedfor you.

**Comment by ms-somanna** [comment]
Will calling forget and forgetAll reset the property values to its factory defaults?

**Comment by anakic** [comment]
Forget just deletes the saved data. The defaults are specified in the configuration, e.g. if you want to track a `Person` object and you want their age to be -1 by default (in case no data for that person is saved) you would write `tracker.Configure<Person>().Property(p => p.Age, -1)`.

In short, as long as you specify the default value for a property (factory settings), deleting the stored data will, in effect, reset to factory settings.

**Comment by ms-somanna** [comment]
Ok I'll try it.
Thanks.

**Comment by SwaroopSomanna** [comment]
> Forget just deletes the saved data. The defaults are specified in the configuration, e.g. if you want to track a `Person` object and you want their age to be -1 by default (in case no data for that person is saved) you would write `tracker.Configure<Person>().Property(p => p.Age, -1)`.
> 
> In short, as long as you specify the default value for a property (factory settings), deleting the stored data will, in effect, reset to factory settings.
> 

How do I set the default value for a bool variable defined in DisplaySettings.cs?

**Comment by anakic** [comment]
Closing this old issue. There are now `Forget(object target)` and `ForgetAll()` methods on the `Tracker` class.
