### ISSUE TITLE
Way 2-4 tracked object id

### ISSUE THREAD

**Issue by innominate227** [anakic/Jot#11]
This question comes only from reading the documentation specifically the "4 ways of initializing TrackingConfiguration".  It looks like each tracked object needs an id associated with it, its clear when using way 1 the id comes from the call to IdenitifyAs.  How is the Id determined in ways 2, 3, and 4?
Thanks

**Comment by anakic** [comment]
Good question! 

Way 2: you get the configuration object as a parameter in the `InitializeConfiguration `method, so you can call IdentifyAs from there. Now that you mention it, the example I gave (the one with the TabControl) is incomplete, it's missing the call to IdentifyAs! It should use the Name of the tabControl instance plus the name of the Window or UserControl that owns it. Something like ... `IdentifyAs( FindRoot(tabControl).Name + tabControl.Name)`

Way3: There is a [TrackingKey] attribute. You would apply this to a property that would be used as the identifier of the object (e.g. Id or Name or etc...)

Way 4: Same as way2, you get the configuration object as a parameter in the InitConfiguration method.


One more thing: if the object being tracked is a singleton, then there's no need for calling IdentifyAs. By default, the object's type name is appended to its identity, so if it's a singleton, the type name is sufficient to identify it.
