### ISSUE TITLE
.NET assemblies are not strong named in the NuGet Package 1.4.0

### ISSUE THREAD

**Issue by jmcrommen** [anakic/Jot#12]
In the NuGet package in the 1.4.0 are not strong named.

**Comment by anakic** [comment]
Right you are. Thanks for pointing it out. I don't think it's much of a problem at the moment, but I will make sure to sign future versions. Was this an issue for you or just a casual observation?

**Comment by jmcrommen** [comment]
Hello, excuse me for the delay in my answer:
I develop a dll to integrate explorer.exe that requires to be signed. During the execution (debug mode) I have the following error:
`System.IO.FileLoadException: 'Could not load file or assembly 'Jot, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'`
I got your project locally and signed it. There may be another solution (I am new to the world c #)

**Comment by simader** [comment]
This issue is also existing in version 1.4.1, please think about it on the next update

**Comment by anakic** [comment]
Yeah, I haven't updated Jot much recently, although I use it a lot. I'll make sure to sign the dll for the next Nuget update.

**Comment by simader** [comment]
in Version 2.0.3 it is still not strong named. Can you do it, and publish a new version? We otherwise would need to strong name it on our side, or we can't use it.

error CS8002: Referenced assembly 'Jot, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by anakic** [comment]
Including or excluding the snk in the source repo took a bit of looking into. In the end, I included it as [per MSDN guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries). I'm still signing the NuGet package with a private code signing certificate. Any comments on this are most welcome.

In any case, as of the current version (v2.1.4.) Jot is strongly named.
