### ISSUE TITLE
Lower Target Framework to or Build Additional Packages for .NET 4.5/4.5.1

### ISSUE THREAD

**Issue by MaybeSacred** [anakic/Jot#13]
Jot currently targets .NET Framework 4.5.2+, however, the solution builds successfully and all tests pass when targeting .NET 4.5 or 4.5.1 as well. Targeting a lower framework increases the number of projects that can use this project (specifically mine, but others would benefit as well).

**Comment by anakic** [comment]
Agreed. There's no reason for it to be higher than 4.5. Care to make a pull request with this change? If not, I'll get to it eventually.

**Comment by bivonblast** [comment]
What is the reason for having the Target Framework in the first place? Seems to work fine for me when using only .netstandard2.0 as a target framework. All 27 tests went through as well as I could run and store data in both WPF and WinForms
