### ISSUE TITLE
Class 'TrackingEventArgs' is never used

### ISSUE THREAD

**Issue by heltonbiker** [anakic/Jot#27]
I was reviewing the sources in order to get an understanding on how the project works, and stumbled upon this warning.

How is the issue expected to be solved:

 - By removing the unused class?
 - By using it somehow?

**Comment by anakic** [comment]
Hey. Yeah, some unused files are still in the repo. It's safe to remove it. Nupkg files should also be removed. Feel free to make a pull request if you like the project and want to contribute.

**Comment by heltonbiker** [comment]
#28 refers to this issue

**Comment by anakic** [comment]
Closing this one as your pull request concludes it.
