### ISSUE TITLE
How to persist ListView?

### ISSUE THREAD

**Issue by ManchesterWuer** [anakic/Jot#38]
I just found that it seems like items in ListView can't be tracked and persisted, do we have a solution here?

**Comment by anakic** [comment]
Jot tracks objects by name, so if you can ensure that each item will have a unique name, you can easily track them. 

However, items in lists are usually dynamically created and deleted by the user, so I'm guessing these objects are part of the business domain. If that's the case, it would probably be better to handle them in the usual way, e.g. with a repository pattern and a database, and not with Jot. 

Jot is more for keeping track of domain-independent stuff. For example, if you're building and application for accounting, you would use a data access layer for storing accounts and invoices, and you would use Jot for keeping track of non-domain stuff like window locations, last entered username, user settings etc.

Does that make sense?
