### ISSUE TITLE
ITrackingAware<T> ConfigureTracking source documentation

### ISSUE THREAD

**Issue by stevemonaco** [anakic/Jot#40]
The XML comment for the return type states the following despite being a void return type:

> Return false to cancel applying state

Also a minor typo on line 9. (persitence -> persistence)

https://github.com/anakic/Jot/blob/be16b070f9c7bbfaba0709d50266268dbc5586a6/Jot/Configuration/ITrackingAware.cs#L17

**Comment by DocBrown101** [comment]
What does the replacement for the configuration look like?

`configuration.Properties(s => new { s.SearchSettings, s.GeneralSettings });`

**Comment by anakic** [comment]
```csharp
class YourClass : Jot.Configuration.ITrackingAware
{
    public void ConfigureTracking(TrackingConfiguration configuration)
    {
        configuration.Properties(s => new { s.SearchSettings, s.GeneralSettings });
    }
}
```

The advantage to using ITrackingAware is that the class itself describes how it wishes its instances to be tracked. Additionally, the configuration object is specific to each instance of `YourClass`, so each instance is free to specify different tracking options independently. 

Configuring on a per-type basis in a central place (e.g. during startup) is best in most situations, I'd advise using ITrackingAware only if different instances of the same class should be tracked differently based on some state.

**Comment by DocBrown101** [comment]
My problem is that I can no longer attach directly to the event "System.Windows.Application.Current.Exit", or have I missed something?

```cs
    using System;
    using Jot.Configuration;

    public class AppSettings : ITrackingAware<AppSettings>
    {
        public SearchSettings SearchSettings { get; set; }

        public GeneralSettings GeneralSettings { get; set; }

        public AppSettings()
        {
            this.SearchSettings = new SearchSettings();
            this.GeneralSettings = new GeneralSettings();
        }

        public void ConfigureTracking(TrackingConfiguration<AppSettings> configuration)
        {
            if (configuration == null)
            {
                throw new ArgumentNullException(nameof(configuration));
            }

            configuration.Properties(s => new { s.SearchSettings, s.GeneralSettings });
            System.Windows.Application.Current.Exit += (s, e) => { configuration.Tracker.Persist(this); };
        }
    }
```

**Comment by anakic** [comment]
This should do it:
```csharp
configuration.PersistOn("Exit", System.Windows.Application.Current);
```
Though there's no difference in the effect, compared to subscribing explicitly like in your code snippet.

**Comment by DocBrown101** [comment]
> ```cs
> configuration.PersistOn("Exit", System.Windows.Application.Current);
> ```

Super thanks, that solved it. Now I could update to version 2.1.7 :)
