### ISSUE TITLE
Confused with the new syntax

### ISSUE THREAD

**Issue by ElektroStudios** [anakic/Jot#41]
Hi. The last time I used JOT was the version 1.41. I updated to version 2.x and I don't know how to translate my old code of old JOT syntax. Someone could help me?:

VB.NET Syntax on a Windows Forms project:

    Private ReadOnly stateTracker As New StateTracker()
    ' ...
    Me.stateTracker.Configure(Me).IdentifyAs(NameOf(Form1)).AddProperties(Of Form)(Function(x) x.DesktopLocation).Apply()
    Me.stateTracker.Configure(Me.ToggleSwitchUserInactivity).IdentifyAs(NameOf(Me.ToggleSwitchUserInactivity)).AddProperty(Of ToggleSwitch)(Function(x) x.Checked).Apply()

I tried this while trying to figure out how to properly write the equivalency :

    Me.stateTracker.Configure(Of ToggleSwitch).Id(Function(x) x.Name).Properties(Function(w) New With {Key w.Checked}).PersistOn(NameOf(Me.FormClosing))

However it throws a exception with this message:

> Expression must project properties as an anonymous class e.g. f => new { f.Height, f.Width } or access a single property e.g. f => f.Text.

[Here](https://github.com/ElektroStudios/Friendly-Challenge-Notifier-for-Hearthstone/blob/3a00b392e6d8e25122b1bafc6686468641b3e9ce/Solution/Friendly%20Challenge%20Notifier/Form1.vb#L80-L84) 🡄 is the full code I need to update to the new syntax. I just track 1 property for 3 different controls, and the form DesktopLocation property.

( the source-code is small and are just 4 lines of code to check... )

### UPDATE

I found a workaround by @anakic at: https://github.com/anakic/Jot/issues/36

Thanks in advance.

**Comment by ElektroStudios** [comment]
I think I finally solved it.  @anakic could you please confirm whether this is the proper / most correct translation of my old code?:

    Private ReadOnly stateTracker As New Tracker()

Then:

    Me.stateTracker.Configure(Of ToggleSwitch).
        Id(Function(x) x.Name).
        Property(Function(w) w.Checked).
        PersistOn(NameOf(ToggleSwitch.CheckChanged)).
        StopTrackingOn(NameOf(ToggleSwitch.Disposed))

    Me.stateTracker.Track(Me.ToggleSwitchUserInactivity)
    Me.stateTracker.Track(Me.ToggleSwitchShowWindow)
    Me.stateTracker.Track(Me.ToggleSwitchPlaySound)

And then:

    Me.stateTracker.Configure(Of Form).
        Id(Function(x) x.Name).
        Property(Function(w) w.DesktopLocation).
        PersistOn(NameOf(Form.Move)).
        StopTrackingOn(NameOf(Form.FormClosing))

    Me.stateTracker.Track(Me)

### C# code translation on-the-fly:

    private readonly Tracker stateTracker = new Tracker();

	this.stateTracker.Configure<ToggleSwitch>.
	    Id((x) => x.Name).
	    Property((w) => w.Checked).
	    PersistOn(nameof(ToggleSwitch.CheckChanged)).
	    StopTrackingOn(nameof(ToggleSwitch.Disposed));

	this.stateTracker.Track(this.ToggleSwitchUserInactivity);
	this.stateTracker.Track(this.ToggleSwitchShowWindow);
	this.stateTracker.Track(this.ToggleSwitchPlaySound);

	this.stateTracker.Configure<Form>.
	    Id((x) => x.Name).
	    Property((w) => w.DesktopLocation).
	    PersistOn(nameof(Form.Move)).
	    StopTrackingOn(nameof(Form.FormClosing));

	this.stateTracker.Track(this);

Thanks in advance.

**Comment by anakic** [comment]
Yep, that looks good. The main thing that's changed in v2 is that you tell Jot how to track a type, rather than a particular object.

**Comment by ElektroStudios** [comment]
Thanks again for your time, issue is solved then I'll close it.
