### ISSUE TITLE
[REQUEST] Include XML documentation file for NuGet package.

### ISSUE THREAD

**Issue by ElektroStudios** [anakic/Jot#42]
@anakic  As it seems you have XML'ed documented all or almost all members in your source-code, then please consider to include the generated XML source documentation file for people that install and use the library through NuGet package. Otherwise it is a real pain to figure out the purpose of each member and for each method parameter without any documentation/explanation shown in the IntelliSense popups.

Thanks for consider it.

**Comment by anakic** [comment]
Oh, I didn't know the xml docs weren't included. I'll make sure to include them in the package.

**Comment by ElektroStudios** [comment]
Thanks so much!
