### ISSUE TITLE
How change config file name.

### ISSUE THREAD

**Issue by pgrzywa** [anakic/Jot#44]
How can I rename a configuration file? 

In Windows forms i have:
"[WindowsFormsApp1.Form1]{Width=1920, Height=1080}.Form1.json"

**Comment by anakic** [comment]
The file name = the Id of the object+namespace.json. If not specified, the type name is used as the Id. 

What would you like to use for the name, is there a particular problem you're having?

**Comment by anakic** [comment]
@pgrzywa You can choose the name with the Id() method, like so:

```csharp
Tracker.Configure<Window>()
			.Id(w => "a different name")
```

This will give you the following filename: "a different name.json".

Are the default names causing issues for you?

**Comment by pgrzywa** [comment]
Thanks.
