### ISSUE TITLE
XML documentation file is missing in distribution

### ISSUE THREAD

**Issue by daniel-lerch** [anakic/Jot#47]
Jot's source code contains XML documentation. However, in [Jot.csproj:33](https://github.com/anakic/Jot/blob/f7c8e5b9eb1c0b1c449d79ca79e04a628acc7e2f/Jot/Jot.csproj#L33) the documentation file is generated only for debug builds. I would recommend to generate them only for release builds instead, so that consumers of the NuGet package can take advantage of documentation in Visual Studio's IntelliSense.

**Comment by anakic** [comment]
Solved in v2.1.11.
