### ISSUE TITLE
Save user settings

### ISSUE THREAD

**Issue by zombiehunter1** [anakic/Jot#51]
Hi  Is there an example of saving user settings,  I've had a good hunt but can't seem to find an example

**Comment by anakic** [comment]
There's [an example](https://github.com/anakic/Jot/blob/b3a41a13c847f7f8dec7243740e909876f80107d/Demo/TestWPF/MainWindow.xaml.cs#L20) in the WPF demo app.

Jot doesn't really know anything about WPF or WinForms, it will track whichever object you tell it to. 

For settings, you would usually have a class with properties that represent the settings, and you would put a [Trackable] attribute on the properties you want to track. Somewhere during your apps startup you would call `tracker.Configure<YourSettingsClass>().Track(theSettingsInstance)`. You could persist on application shutdown or e.g. on PropertyChanged. You could make the instance of the settings object available to the rest of the application through an IOC container or via a static property.

A simple example in the readme would be in order, though... I'll see about adding that when I can get to it.
