### ISSUE TITLE
Does DefaultValue Attribute implementation work?

### ISSUE THREAD

**Issue by bcssov** [anakic/Jot#57]
Are you sure the default value attribute implementation works?

Namely I put the default value attribute but this piece of logic doesn't read it:
https://github.com/anakic/Jot/blob/488b9e70493c060dca5b4e1fd75d561f7cceda27/Jot/Configuration/TrackingConfiguration.cs#L107-L108

**Comment by anakic** [comment]
@bcssov can confirm this is a bug. Fixed it and will push a new version today.

**Comment by anakic** [comment]
@bcssov new version (2.1.13) pushed to github and nuget. Can you confirm if it solves this bug for you?

**Comment by bcssov** [comment]
Works fine, closing.
