### ISSUE TITLE
Crash while persisting

### ISSUE THREAD

**Issue by jpobst** [anakic/Jot#6]
I am using (and loving!) Jot in a WPF app in the Windows Store.  Their built-in crash reporting is returning this stack trace of a crash:

```
Frame	Image	Function	Offset
0	mscorlib_ni	System.IO.__Error.WinIOError	0x208	
1	mscorlib_ni	System.IO.FileStream.Init	0x2E1	
2	mscorlib_ni	System.IO.FileStream..ctor	0x43	
3	mscorlib_ni	System.IO.StreamWriter.CreateFile	0x4A	
4	mscorlib_ni	System.IO.StreamWriter..ctor	0x4A	
5	mscorlib_ni	System.IO.File.InternalWriteAllText	0x41	
6	mscorlib_ni	System.IO.File.WriteAllText	0x2C	
7	Jot	Jot.Storage.Stores.JsonFileStore.SaveValues	0xEF	
8	Jot	Jot.Storage.PersistentStoreBase.CommitChanges	0x19	
9	Jot	Jot.TrackingConfiguration.Persist	0x1B5	
10	Jot	Jot.TrackingConfiguration._RegisterPersistTrigger_b__58_1	0xC	
11	mscorlib_ni	System.EventHandler.Invoke	0x2	
12	PresentationFramework_ni	System.Windows.Window.OnLocationChanged	0xCBB09F	
13	PresentationFramework_ni	System.Windows.Window.WmMoveChangedHelper	0x51	
```

Unfortunately they don't provide the actual exception message, but the issue appears to be the `File.WriteAllText` in `JsonFileStore.SaveValues`.  There definitely needs to be some error handling around this call, since it could fail for example if the user doesn't have permission to write there or the disk is full.

**Comment by anakic** [comment]
Hey Jpobst, glad you're liking Jot! I never used it for windows store applications, nice to hear it's working nicely! About the exception - yeah, writing to the file could certainly fail for a number of reasons. I'm not sure how Jot could recover from an error in that line, though. Seems to me that there's no backup option so propagating the exception seems reasonable. Any suggestion on what the error handler should do if saving the data to the file fails?

**Comment by jpobst** [comment]
Yeah, I can understand that.  In my case I'm only tracking window position so I'm fine if it silently fails, but if I was persisting something more important I would definitely want to know about the failure.

I guess my issue is that I'm using `Tracker.Configure (this).Apply ();` so it's all happening in the background and I don't get a chance to handle the error.  Instead, my app just crashes.

Perhaps the `TrackingConfiguration` needs a fluent method that can set an exception handling delegate?

**Comment by anakic** [comment]
Ah, I get it. Yeah, Apply() saves what it can and ignores what it can't, but yeah, that might not be what you want in all situations. I like your suggestion about adding a method for registering an error handler. Wanna make a pull request with this change maybe?
