### ISSUE TITLE
Persisting a list

### ISSUE THREAD

**Issue by zombiehunter1** [anakic/Jot#60]
Hi, is it possible to persist a list  I have defined a property but nothing gets saved on a persist event,  I've checked the demos but can't
see any example of this,  can you point me in the right direction  Cheers

`[Trackable]
            public List<ZoneInfo> ZoneInfos;`

`public class ZoneInfo
    {
 
        public float Cost { get; set; }
      
        public int Radius { get; set; }
      
        public string Name { get; set; }
    }`

**Comment by anakic** [comment]
Hmm, the list itself shouldn't be a problem, but I think the problem in your snippet of code might be that ZoneInfos is a field and not a property. Can you turn it into a property and post back if that was the problem?

**Comment by zombiehunter1** [comment]
Oh my,  I could not see my simple problem,  Thanks so much
