### ISSUE TITLE
Jot  Abstractions upgrade 7.1, it will report an error

### ISSUE THREAD

**Issue by JiaoZaiShiJie** [anakic/Jot#65]
Microsoft.Extensions.Logging >=7.1    thorw error

Void Jot.Tracker..ctor(Jot.Storage.IStore, Microsoft.Extensions.Logging.ILogger`1)”。

If you switch to 7.0 everything is OK 

I've tested it many times, I don't know if this is the case in your area

**Comment by anakic** [comment]
Thanks for the heads up. I'll check it out. I'm tempted to remove the logging dependency altogether. It's causing trouble and it's not really necessary in production.

**Comment by JiaoZaiShiJie** [comment]
Thanks for your reply, it would be best if we could remove the log dependency completely

**Comment by anakic** [comment]
@JiaoZaiShiJie I removed the logging dependency and pushed version 2.1.17. Let me know if you're still running into any issues.

**Comment by JiaoZaiShiJie** [comment]
Thank you for all your hard work, I'm using it now without any problems
